### ISSUE TITLE
Build unsuccessful when using SNS3

### ISSUE THREAD

**Issue by BurtonYu** [neje/ns3-network-performance-tool-v2#3]
I am using SNS3 (based on NS3 3.29, can be found in https://github.com/sns3/sns3-satellite) to do some simulations. But when I build NS3 program with both this tool and SNS3, I get an error like this:

../src/applications/helper/stats-helper.cc:44:1: error: ‘StatsSourceHelper’ does not name a type; did you mean ‘StatsHelper’?
 StatsSourceHelper::StatsSourceHelper (std::string protocol, Address address)
 ^~~~~~~~~~~~~~~~~
 StatsHelper
../src/applications/helper/stats-helper.cc:52:1: error: ‘StatsSourceHelper’ has not been declared
 StatsSourceHelper::SetAttribute (std::string name, const AttributeValue &value)
 ^~~~~~~~~~~~~~~~~
../src/applications/helper/stats-helper.cc: In function ‘void ns3::SetAttribute(std::__cxx11::string, const ns3::AttributeValue&)’:
../src/applications/helper/stats-helper.cc:54:3: error: ‘m_factory’ was not declared in this scope
   m_factory.Set (name, value);
   ^~~~~~~~~
../src/applications/helper/stats-helper.cc: At global scope:
../src/applications/helper/stats-helper.cc:57:1: error: ‘ApplicationContainer’ does not name a type; did you mean ‘Application’?
 ApplicationContainer
 ^~~~~~~~~~~~~~~~~~~~
 Application
../src/applications/helper/stats-helper.cc:63:1: error: ‘ApplicationContainer’ does not name a type; did you mean ‘Application’?
 ApplicationContainer
 ^~~~~~~~~~~~~~~~~~~~
 Application
../src/applications/helper/stats-helper.cc:70:1: error: ‘ApplicationContainer’ does not name a type; did you mean ‘Application’?
 ApplicationContainer
 ^~~~~~~~~~~~~~~~~~~~

......

Waf: Leaving directory `/home/yutao/ns-3/ns-allinone-3.29/ns-3.29/build'
Build failed
 -> task in 'ns3-applications' failed with exit status 1 (run with -v to display more information)

Could you give me some advice?

**Comment by neje** [comment]
It seems that header file is missing. Did you copy appropriate version of "wscript" file from the folder "release specific files" to the ".../src/applications" folder in your ns-3 installation. Since you use ns-3.29, copy the file "ns3-network-performance-tool-v2/release specific files/ns3.29 & ns3.30 & ns3.30.1/src/applications/wscript" from this repository to to the ".../src/applications" folder in your ns-3 installation (and replace existing wscript file from your ns-3 installation). 
If this is not the case, plese provide complete build error text.

**Comment by BurtonYu** [comment]
Thank you for your reply. I indeed copy all the files as required, in fact I have already build successfully in NS3 3.29. But when I copy the files required by SNS3 into the program, build errors come out. The same happens when I try to copy this tool into SNS3 environment which is already builded successfully.

Here is the complete build text: [log.txt](https://github.com/neje/ns3-network-performance-tool-v2/files/4841688/log.txt)

**Comment by neje** [comment]
I got the same compilation result using "./waf build". If "./waf build -j 6" is used (as required at https://github.com/sns3/sns3-satellite), slightly different results are obtained. But there seems to be some overlap in the file or class names that I am currently unable to find. I'll try to fix that in the next few days.

**Comment by BurtonYu** [comment]
OK, thanks : )

**Comment by neje** [comment]
I found an overlap in the name of the files and classes from this repository and from https://github.com/sns3/stats, which is a part of SNS3. So it is necessary to change the file and class names so that there are no compilation errors.
I have created a new repository https://github.com/neje/npaf with renamed files. But due to my laziness, I didn't change the class names (lots of changes should be done to be consistent). Instead, besides usual "namespace ns3" used in ns-3 simulator code, I used additional "namespace npaf" in the code for this new repository, so all class names now have the complete prefix "ns3::npaf::".
I will add some examples to this new repository later ... but all is the same instead installation is now moved to contrib folder, and you should add "npaf::" as prefix for class names.

**Comment by BurtonYu** [comment]
I see. Thank you for your excellent work again！
